# -*- coding: utf-8 -*-
"""bin_gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-B6z5khX055LZoxNZ9YHjZvWsq_Emfq
"""



import struct
from google.colab import files

samples = [682, 581, -316]

# Convert to little-endian signed 16-bit and join all bytes
binary_data = b''.join(struct.pack('<h', sample) for sample in samples)

# Save to a file
with open("output.bin", "wb") as f:
    f.write(binary_data)

# Download the file
files.download("output.bin")