# -*- coding: utf-8 -*-
"""datfileanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilcoxN8lD4OiQRBVIfb3aK7r0jOpcufC
"""



from google.colab import files
import numpy as np

# Step 1: Upload the .dat file
uploaded = files.upload()

# Step 2: Get the file name of the uploaded file
file_name = list(uploaded.keys())[0]

# Step 3: Read and process the .dat file
with open(file_name, 'r') as file:
    content = file.read()

# Split the content by commas, newlines, and spaces, and filter out empty strings
data = [float(value) for value in content.replace('\n', ',').replace(' ', ',').split(',') if value]

# Convert list to a NumPy array
data = np.array(data)

# Get the highest value, lowest value, and total number of values
highest_value = np.max(data)
lowest_value = np.min(data)
total_values = data.size

# Print the results
print(f"Highest value: {highest_value}")
print(f"Lowest value: {lowest_value}")
print(f"Total number of values: {total_values}")